defaults: {}
server:
  ignore_certs: false
  url: https://galaxy-qa.ansible.com
content_path: ~/.ansible/collections/ansible_collections
options:
  local_tmp: ~/.ansible/tmp
  role_skeleton_ignore:
    - ^.git$
    - ^.*/.git_keep$
  role_skeleton_path: null
  verbosity: 0
version: 1
